name: Deploy to GitHub Pages

# 📌 Déclenchement : à chaque push sur main
on:
  push:
    branches:
      - master

# 🚀 Job unique pour le déploiement
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./     # Le dossier à publier (ici, la racine du projet)
